name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
          cache: 'npm'
      
      - name: Install dependencies with npm ci
        run: npm ci

      - name: Static HTML export with Nuxt
        run: npm run generate

      # Uncomment the following lines if you have unit tests to run
      # - name: Run unit tests
      #   run: npm run test
