name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Clear npm cache
        run: npm cache clean --force 
        
      - name: Install dependencies
        run: npm install

      - name: Static HTML export with Nuxt
        run: npm run generate
